name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }}, Django${{ matrix.django-version }}

    strategy:
      matrix:
        # todo 3.8
        python-version: [3.6]
        # todo more django versions
        django-version: [">=1.11,<2"]

    steps:
    - uses: actions/checkout@v2
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip --disable-pip-version-check install -r dev-requirements.txt
        pip install "Django${{ matrix.django-version }}"
    # todo lint
    - name: Run tests
      run: |
        pytest
